### ISSUE TITLE
clarification on the last check in the checklist? `Benchmarking information is provided for examples`

### ISSUE THREAD

**Issue by zhao-cy** [nmind/coding-standards-certification#29]
Hi there,

Thank you very much for building this checklist! I hope to apply this checklist to software we are wroking on. When I'm going through the checklist, I'm not totally sure about the last check in the `Testing` list: `Benchmarking information is provided for examples`. Could you please explain a bit more about the expectation of this check? 

For example, would this be sufficient: `With the YAML file provided, this may take ~1.5 min for ~2500 jobs.` - this is from the [docs of the software we're working on](https://pennlinc-babs.readthedocs.io/en/latest/jobs.html#recommended-way-to-check-job-status-including-failed-job-auditing). This runtime is for a specific function in the software, not the entire runtime of all the steps. The runtime is not generated automatically when the docs is building, though.

I'm tagging @tsalo here as he also hopes to know the answer.

Thanks in advance!
Chenying

**Comment by gkiar** [comment]
Thanks for reaching out! I think benchmarking information in this context is intended to capture whatever performance targets are relevant: either things like runtime ( as is relevant here ) or something like the "accuracy" of a model, e.g..

I would say that what you described *does* fit the bill and be sufficient!

**Comment by zhao-cy** [comment]
Perfect! Thank you for the clarification + quick reply, Greg!!
